-- Run this in Supabase SQL Editor

create table public.generated_quizzes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  file_name text,
  model_id text,
  mode text,
  topic_summary text,
  questions jsonb not null
);

-- Optional: Enable Row Level Security (RLS) if you want public access
alter table public.generated_quizzes enable row level security;

-- Policy to allow anyone (anon) to insert quizzes
create policy "Enable insert for everyone"
on public.generated_quizzes
for insert
to anon
with check (true);

-- Policy to allow anyone to read (optional, if you want a leaderboard later)
create policy "Enable read for everyone"
on public.generated_quizzes
for select
to anon
using (true);