
-- JALANKAN INI DI SUPABASE > SQL EDITOR

-- 1. Buat Tabel History Kuis (Untuk Aplikasi Mikir)
create table if not exists public.generated_quizzes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  file_name text,
  model_id text,
  mode text,
  topic_summary text,
  questions jsonb not null
);

-- 2. Buat Tabel Notes (Untuk Integrasi dengan App Catatanmu)
-- Pastikan kolom 'title' dan 'content' ada agar Mikir bisa membacanya.
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  content text, 
  tags text[] 
);

-- 3. KONFIGURASI KEAMANAN (RLS)
-- Kita buka akses untuk 'anon' (anonymous/tanpa login) agar aplikasi web bisa baca/tulis.
-- WARNING: Ini berarti siapa saja yang punya Anon Key bisa baca data ini. 
-- Aman untuk project pribadi/belajar.

-- Enable RLS
alter table public.generated_quizzes enable row level security;
alter table public.notes enable row level security;

-- Bersihkan policy lama (jika ada) untuk menghindari error
drop policy if exists "Public Access Quizzes" on public.generated_quizzes;
drop policy if exists "Public Access Notes" on public.notes;

-- Buat Policy: Izinkan SELECT, INSERT, UPDATE, DELETE untuk Generated Quizzes
create policy "Public Access Quizzes" 
on public.generated_quizzes 
for all 
to anon 
using (true) 
with check (true);

-- Buat Policy: Izinkan SELECT, INSERT, UPDATE, DELETE untuk Notes
create policy "Public Access Notes" 
on public.notes 
for all 
to anon 
using (true) 
with check (true);
