
/**
 * ==========================================
 * MIKIR CLOUD CLIENT (Supabase Service V2)
 * ==========================================
 * Centralized Data Access Layer.
 * Mengelola semua interaksi database dengan struktur yang rapi.
 */

import { getSupabaseClient } from "../lib/supabaseClient";
import { Question, CloudNote } from "../types";

// --- 1. SCHEMA DEFINITION ---
export const SUPABASE_SCHEMA_SQL = `
-- =========================================================
-- MIKIR DATABASE SCHEMA (NEURO EDITION)
-- Copy & Paste script ini di Supabase > SQL Editor
-- =========================================================

-- 1. Tabel Quiz (Menyimpan hasil generate AI)
CREATE TABLE IF NOT EXISTS public.generated_quizzes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  file_name text,
  model_id text,
  mode text,
  topic_summary text,
  questions jsonb NOT NULL
);

-- 2. Tabel Neuro Notes (Sumber Catatan)
create table if not exists public.neuro_notes (
  id text primary key,
  timestamp bigint,
  topic text,
  mode text,
  content text,
  provider text
);

-- 3. Reset Permissions (Nuclear Option)
-- Matikan RLS dulu untuk reset
alter table public.generated_quizzes disable row level security;
alter table public.neuro_notes disable row level security;

-- Nyalakan RLS kembali
alter table public.generated_quizzes enable row level security;
alter table public.neuro_notes enable row level security;

-- 4. KEBIJAKAN "GOD MODE" (CRUD BEBAS)
-- Ini mengizinkan Select, Insert, Update, Delete untuk siapa saja yang punya API Key.
drop policy if exists "God Mode Quizzes" on public.generated_quizzes;
create policy "God Mode Quizzes" on public.generated_quizzes for all using (true) with check (true);

drop policy if exists "God Mode Notes" on public.neuro_notes;
create policy "God Mode Notes" on public.neuro_notes for all using (true) with check (true);

-- 5. Aktifkan Realtime
alter publication supabase_realtime add table public.neuro_notes;
`;

// --- 2. TYPES ---
export interface SupabaseConfig {
  url: string;
  key: string;
}

interface QuizRecord {
  id: number;
  created_at: string;
  file_name: string;
  model_id: string;
  mode: string;
  topic_summary: string;
  questions: Question[];
}

// --- 3. THE CLIENT ---
export const MikirCloud = {
  
  /**
   * Mendapatkan raw client instance (private helper)
   */
  _client(config: SupabaseConfig) {
    return getSupabaseClient(config.url, config.key);
  },

  // --- QUIZ MODULE ---
  quiz: {
    async list(config: SupabaseConfig) {
      const sb = MikirCloud._client(config);
      const { data, error } = await sb
        .from('generated_quizzes')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw new Error(`Gagal mengambil quiz: ${error.message}`);
      
      // Transform snake_case DB to camelCase App
      return (data as QuizRecord[]).map(item => ({
        id: item.id,
        fileName: item.file_name,
        modelId: item.model_id,
        mode: item.mode,
        date: item.created_at,
        questionCount: Array.isArray(item.questions) ? item.questions.length : 0,
        topicSummary: item.topic_summary,
        questions: item.questions,
        isCloud: true
      }));
    },

    async create(config: SupabaseConfig, payload: any) {
      const sb = MikirCloud._client(config);
      
      // Mapping App Data -> DB Columns
      const dbPayload = {
        file_name: payload.fileName || payload.file_name,
        model_id: payload.modelId || payload.model_id,
        mode: payload.mode,
        topic_summary: payload.topicSummary || payload.topic_summary,
        questions: payload.questions
      };

      const { error } = await sb.from('generated_quizzes').insert(dbPayload);
      if (error) throw new Error(`Gagal upload: ${error.message}`);
      return true;
    },

    async delete(config: SupabaseConfig, id: number | string) {
      const sb = MikirCloud._client(config);
      const { error } = await sb.from('generated_quizzes').delete().eq('id', id);
      if (error) throw new Error(`Gagal hapus: ${error.message}`);
      return true;
    },

    async updateQuestions(config: SupabaseConfig, id: number | string, questions: Question[]) {
      const sb = MikirCloud._client(config);
      const { error } = await sb
        .from('generated_quizzes')
        .update({ questions: questions })
        .eq('id', id);
      
      if (error) throw new Error(`Gagal update soal: ${error.message}`);
      return true;
    }
  },

  // --- NOTES MODULE (Updated to 'neuro_notes') ---
  notes: {
    async list(config: SupabaseConfig): Promise<CloudNote[]> {
      const sb = MikirCloud._client(config);
      try {
        // Fetch from neuro_notes
        const { data, error } = await sb
          .from('neuro_notes')
          .select('*')
          .order('timestamp', { ascending: false })
          .limit(20);
        
        if (error) {
          console.warn("Notes fetch warning:", error.message);
          return [];
        }

        if (!data) return [];

        // Map neuro_notes schema to App's CloudNote interface
        // Schema: id (text), timestamp (int8), topic (text), mode (text), content (text), provider (text)
        return data.map((item: any) => {
          
          // --- LOGIKA PEMBERSIHAN JUDUL (FIX TITLE OVERFLOW) ---
          let displayTitle = item.topic;
          const rawContent = item.content || "";

          // 1. Jika topic kosong/null, ambil potongan content
          if (!displayTitle || displayTitle.trim() === "") {
             // Ambil baris pertama atau 50 karakter pertama
             const firstLine = rawContent.split('\n')[0];
             displayTitle = firstLine.substring(0, 50);
             if (rawContent.length > 50) displayTitle += "...";
          } 
          // 2. Jika topic ada tapi SANGAT PANJANG (indikasi user salah save content ke topic)
          else if (displayTitle.length > 80) {
             displayTitle = displayTitle.substring(0, 80) + "...";
          }

          return {
            id: item.id,
            title: displayTitle || "Catatan Tanpa Judul", // Judul yang sudah dibersihkan
            content: rawContent,
            // Convert timestamp (bigint) to ISO string for UI
            created_at: item.timestamp ? new Date(Number(item.timestamp)).toISOString() : new Date().toISOString(),
            // Map metadata to tags
            tags: [item.mode, item.provider].filter(Boolean)
          };
        });

      } catch (e) {
        console.error("Notes fetch error:", e);
        return [];
      }
    }
  },

  // --- SYSTEM MODULE ---
  system: {
    async checkConnection(config: SupabaseConfig) {
      const sb = MikirCloud._client(config);
      
      // Tes koneksi dengan mengambil 1 baris ID saja (ringan)
      const { error } = await sb.from('generated_quizzes').select('id').limit(1);

      if (error) {
        // Deteksi error spesifik: Tabel tidak ada (42P01 di Postgres)
        if (error.message.includes('relation') && error.message.includes('does not exist')) {
          return { connected: true, schemaMissing: true, message: "Tabel belum dibuat." };
        }
        return { connected: false, schemaMissing: false, message: error.message };
      }

      return { connected: true, schemaMissing: false, message: "OK" };
    }
  }
};
