
/**
 * ==========================================
 * MIKIR CLOUD CLIENT (Supabase Service V2)
 * ==========================================
 * Centralized Data Access Layer.
 * Mengelola semua interaksi database dengan struktur yang rapi.
 */

import { getSupabaseClient } from "../lib/supabaseClient";
import { Question, CloudNote, LibraryItem } from "../types";

// --- 1. SCHEMA DEFINITION ---
export const SUPABASE_SCHEMA_SQL = `
-- =========================================================
-- MIKIR DATABASE SCHEMA (NEURO EDITION)
-- Copy & Paste script ini di Supabase > SQL Editor
-- =========================================================

-- 1. Tabel Quiz (Menyimpan hasil generate AI)
CREATE TABLE IF NOT EXISTS public.generated_quizzes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  file_name text,
  model_id text,
  mode text,
  topic_summary text,
  questions jsonb NOT NULL
);

-- 2. Tabel Library Materi (PDF/Uploads)
create table if not exists public.library_materials (
  id text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  content text,
  processed_content text,
  file_type text,
  tags text[]
);

-- 3. Tabel Neuro Notes (Catatan Kecil / Corat-coret)
create table if not exists public.neuro_notes (
  id text primary key,
  timestamp bigint,
  topic text,
  mode text,
  content text,
  provider text
);

-- 4. Reset Permissions (Nuclear Option)
alter table public.generated_quizzes disable row level security;
alter table public.library_materials disable row level security;
alter table public.neuro_notes disable row level security;

alter table public.generated_quizzes enable row level security;
alter table public.library_materials enable row level security;
alter table public.neuro_notes enable row level security;

-- 5. KEBIJAKAN "GOD MODE" (CRUD BEBAS)
drop policy if exists "God Mode Quizzes" on public.generated_quizzes;
create policy "God Mode Quizzes" on public.generated_quizzes for all using (true) with check (true);

drop policy if exists "God Mode Library" on public.library_materials;
create policy "God Mode Library" on public.library_materials for all using (true) with check (true);

drop policy if exists "God Mode Notes" on public.neuro_notes;
create policy "God Mode Notes" on public.neuro_notes for all using (true) with check (true);

-- 6. Aktifkan Realtime
alter publication supabase_realtime add table public.neuro_notes;
alter publication supabase_realtime add table public.library_materials;
`;

// --- 2. TYPES ---
export interface SupabaseConfig {
  url: string;
  key: string;
}

interface QuizRecord {
  id: number;
  created_at: string;
  file_name: string;
  model_id: string;
  mode: string;
  topic_summary: string;
  questions: Question[];
}

// --- 3. THE CLIENT ---
export const MikirCloud = {
  
  _client(config: SupabaseConfig) {
    return getSupabaseClient(config.url, config.key);
  },

  // --- QUIZ MODULE ---
  quiz: {
    async list(config: SupabaseConfig) {
      const sb = MikirCloud._client(config);
      const { data, error } = await sb
        .from('generated_quizzes')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw new Error(`Gagal mengambil quiz: ${error.message}`);
      
      return (data as QuizRecord[]).map(item => ({
        id: item.id,
        fileName: item.file_name,
        modelId: item.model_id,
        mode: item.mode,
        date: item.created_at,
        questionCount: Array.isArray(item.questions) ? item.questions.length : 0,
        topicSummary: item.topic_summary,
        questions: item.questions,
        isCloud: true
      }));
    },

    async create(config: SupabaseConfig, payload: any) {
      const sb = MikirCloud._client(config);
      const dbPayload = {
        file_name: payload.fileName || payload.file_name,
        model_id: payload.modelId || payload.model_id,
        mode: payload.mode,
        topic_summary: payload.topicSummary || payload.topic_summary,
        questions: payload.questions
      };
      const { error } = await sb.from('generated_quizzes').insert(dbPayload);
      if (error) throw new Error(`Gagal upload: ${error.message}`);
      return true;
    },

    async delete(config: SupabaseConfig, id: number | string) {
      const sb = MikirCloud._client(config);
      const { error } = await sb.from('generated_quizzes').delete().eq('id', id);
      if (error) throw new Error(`Gagal hapus: ${error.message}`);
      return true;
    },

    async updateQuestions(config: SupabaseConfig, id: number | string, questions: Question[]) {
      const sb = MikirCloud._client(config);
      const { error } = await sb.from('generated_quizzes').update({ questions: questions }).eq('id', id);
      if (error) throw new Error(`Gagal update soal: ${error.message}`);
      return true;
    }
  },

  // --- LIBRARY MODULE (New Separate Table) ---
  library: {
    async list(config: SupabaseConfig): Promise<LibraryItem[]> {
      const sb = MikirCloud._client(config);
      const { data, error } = await sb
        .from('library_materials')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) {
        console.error("Library Fetch Error:", error);
        return [];
      }
      if (!data) return [];

      return data.map((item: any) => ({
        id: item.id,
        title: item.title,
        content: item.content,
        processedContent: item.processed_content, // Map DB snake_case to App camelCase
        type: (item.file_type as any) || 'text',
        tags: item.tags || [],
        created_at: item.created_at
      }));
    },

    async create(config: SupabaseConfig, item: LibraryItem) {
      const sb = MikirCloud._client(config);
      const dbPayload = {
        id: String(item.id),
        title: item.title,
        content: item.content,
        processed_content: item.processedContent,
        file_type: item.type,
        tags: item.tags,
        created_at: new Date().toISOString()
      };
      const { error } = await sb.from('library_materials').insert(dbPayload);
      if (error) throw new Error(`Gagal simpan ke Library: ${error.message}`);
      return true;
    },

    async delete(config: SupabaseConfig, id: string | number) {
      const sb = MikirCloud._client(config);
      const { error } = await sb.from('library_materials').delete().eq('id', String(id));
      if (error) throw new Error(`Gagal hapus materi: ${error.message}`);
      return true;
    },

    async update(config: SupabaseConfig, id: string | number, updates: Partial<LibraryItem>) {
      const sb = MikirCloud._client(config);
      const dbUpdates: any = {};
      if (updates.processedContent) dbUpdates.processed_content = updates.processedContent;
      if (updates.content) dbUpdates.content = updates.content;
      
      const { error } = await sb.from('library_materials').update(dbUpdates).eq('id', String(id));
      if (error) throw new Error(`Gagal update materi: ${error.message}`);
      return true;
    }
  },

  // --- NOTES MODULE (Legacy / Scratchpad) ---
  notes: {
    async list(config: SupabaseConfig): Promise<CloudNote[]> {
      const sb = MikirCloud._client(config);
      try {
        const { data, error } = await sb
          .from('neuro_notes')
          .select('*')
          .order('timestamp', { ascending: false });
        
        if (error) return [];
        return data ? data.map((item: any) => ({
            id: item.id,
            title: item.topic || "Note",
            content: item.content,
            created_at: item.timestamp ? new Date(Number(item.timestamp)).toISOString() : new Date().toISOString(),
            tags: [item.mode, item.provider].filter(Boolean)
        })) : [];
      } catch (e) { return []; }
    },

    async create(config: SupabaseConfig, payload: any) {
        const sb = MikirCloud._client(config);
        const { error } = await sb.from('neuro_notes').insert(payload);
        if (error) throw new Error(`Gagal simpan note: ${error.message}`);
        return true;
    },

    async delete(config: SupabaseConfig, id: string | number) {
        const sb = MikirCloud._client(config);
        const { error } = await sb.from('neuro_notes').delete().eq('id', id);
        if (error) throw new Error(`Gagal hapus note: ${error.message}`);
        return true;
    }
  },

  // --- SYSTEM MODULE ---
  system: {
    async checkConnection(config: SupabaseConfig) {
      const sb = MikirCloud._client(config);
      const { error } = await sb.from('generated_quizzes').select('id').limit(1);
      if (error) {
        if (error.message.includes('relation') && error.message.includes('does not exist')) {
          return { connected: true, schemaMissing: true, message: "Tabel belum dibuat." };
        }
        return { connected: false, schemaMissing: false, message: error.message };
      }
      return { connected: true, schemaMissing: false, message: "OK" };
    }
  }
};
